feat: Validation rule for metering point type
Energinet-DataHub/opengeh-wholesale pull request #1523
Opened 2023-10-11 18:50 UTC by RasmusGraabaek

This pull request will add a validation rule for the "MeteringPointType" attribute defined in the aggregated measure data request from EDI. It checks that the input is of the specified "codes" and returns an error if not.

2023-10-13 11:35 UTC, BjarkeMeier commented on source/dotnet/wholesale-api/Edi.UnitTests/Builders/AggregatedTimeSeriesRequestBuilder.cs
> +        _meteringPointType = meteringPointType;
"E18" is not in the vocabulary of wholesale anymore. Please use "consumption", "production" etc.

2023-10-13 11:36 UTC, BjarkeMeier commented on source/dotnet/wholesale-api/Edi.UnitTests/Validators/AggregatedTimeSeriesRequestValidatorTests.cs
> +    private const string ValidMeteringPointType = "E18";
See comment in builder.

2023-10-13 11:36 UTC, BjarkeMeier commented on source/dotnet/wholesale-api/Edi.UnitTests/Validators/MeteringPointTypeValidatorTests.cs
> +    [InlineData("E20")]
See other comments.

2023-10-16 08:01 UTC, ebbeknudsen requested changes

2023-10-16 12:12 UTC, ebbeknudsen approved these changes

2023-10-16 12:22 UTC, merged