feat: Balance Responsible validation on Aggregarted Time Serie Request
Energinet-DataHub/opengeh-wholesale pull request #1539
Opened 2023-10-17 08:38 UTC by MadsDue

Add balance responsible validation to AggregatedTimeSeriesRequest, which validates that the balance responsible field is correct, if the request is sent by an balance responsible

Tasks: 
- [ ] update AggregatedTimeSeriesRequest contract with Balance Responsible id
- [ ] Implement validation rule which validates the following:
  - [ ] if sender role is balanceansvarlig, the balanceResponsibleParty present and a valid GLN/EIC format.
  - [ ] Then balanceResponsibleParty must match senderNumber
 
References:
https://github.com/Energinet-DataHub/opengeh-edi/pull/566

2023-10-17 13:37 UTC, RasmusGraabaek submitted a review, later dismissed

2023-10-18 07:56 UTC, ebbeknudsen requested changes

2023-10-18 07:56 UTC, ebbeknudsen commented on source/dotnet/wholesale-api/Edi.UnitTests/Validators/BalanceResponsibleValidatorTest.cs
> +    public void Validate_WhenRequesterIsBalanceResponsibleAndMissingBalanceResponsibleField_ReturnsExceptedValidationError()
Excepted -> Expected :) (i hele filen)

- [ ] Rename excepted -> expected

2023-10-18 07:56 UTC, ebbeknudsen commented on source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/BalanceResponsibleValidationRule.cs
> +        if (subject.RequestedByActorRole == BalanceResponsibleRole)
Evt. invert `if` for at reducere nesting. Det synes jeg er nemmere at læse, men det er op til dig

2023-10-18 07:56 UTC, ebbeknudsen commented on source/dotnet/wholesale-api/Edi/Validation/AggregatedTimeSerie/Rules/BalanceResponsibleValidationRule.cs
> +    private static bool IsValidActorRoleFormat(string energySupplierId)
`energySupplierId` -> `balanceResponsibleId`.

Skal vi evt. lave noget fælles der kan validere gln / eic nummer? Vi gør det samme i BalanceResponsible og EnergySupplier valideringen

- [ ] Rename `energySupplierId` -> `balanceResponsibleId`

2023-10-18 08:24 UTC, ebbeknudsen approved these changes

2023-10-18 08:45 UTC, merged