experimental: Use EF Core as DB SQL mapper.
Energinet-DataHub/opengeh-wholesale pull request #2504
Opened 2024-07-02 19:06 UTC by defectiveAi

# Description

## Pull-request quality

- [ ] The title adheres to [this guide](https://github.com/Mech0z/GitHubGuidelines)
- [ ] Tests are written and executed locally
- [ ] Subsystem tests have been tested (by manually deploying to `dev_002`)

2024-07-03 06:26 UTC, FirestarJes requested changes

2024-07-03 06:35 UTC, michaelmajgaard commented on source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Experimental/DatabricksSqlQueryExecutor.cs
> +            // TODO: Do not ask...
Why dis todo?

2024-07-03 06:37 UTC, BjarkeMeier commented on source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Experimental/DatabricksSqlQueryExecutor.cs
> +            // TODO: Do not ask...
Oh man, it asked just one single thing for you not to do. And you did it - you asked! 😆

2024-07-03 12:16 UTC, defectiveAi commented on source/dotnet/wholesale-api/CalculationResults/CalculationResults.Infrastructure/Experimental/DatabricksSqlQueryExecutor.cs
> +            // TODO: Do not ask...
What todo, I see no todo...

2024-07-08 12:02 UTC, FirestarJes submitted a review, later dismissed

2024-07-08 12:41 UTC, michaelmajgaard approved these changes

2024-07-08 12:41 UTC, merged